FROM redis:alpine

WORKDIR /healthchecks

COPY healthchecks/redis.sh .

RUN chmod +x redis.sh

VOLUME [ "/data" ]

HEALTHCHECK --interval=30s --timeout=5s --retries=3 CMD /healthchecks/redis.sh

CMD ["redis-server", "--dir", "/data"]
