apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  selector:
    matchLabels:
      app: db
  replicas: 1
  template:
    metadata:
      name: db
      labels:
        app: db
    spec:
      containers:
        - image: europe-west9-docker.pkg.dev/tuto-kube/voting-image/db
          name: db
          volumeMounts:
            - name: db-data
              mountPath: /data
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "db"
      volumes:
        - name: db-data
          gcePersistentDisk:
            pdName: db-disk
            fsType: ext4
