apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: db
      labels:
        app: db
    spec:
      containers:
      - image: europe-west9-docker.pkg.dev/login-ue-cloud-k8s/voting-image/db
        name: db
        volumeMounts:
          - mountPath: "/var/lib/postgresql/data"
            subPath: data
            name: db-data
        env:
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "postgres"
          - name: POSTGRES_DB
            value: "db"
      volumes:
        - name: db-data
          gcePersistentDisk:
            pdName: db-disk
            fsType: ext4
  selector:
    matchLabels:
      app: db
