apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 3
  template:
    metadata:
      name: redis
      labels:
        app: redis
    spec:
      containers:
      - image: europe-west9-docker.pkg.dev/login-ue-cloud-k8s/voting-image/redis
        name: redis
  selector:
    matchLabels:
      app: redis
