apiVersion: batch/v1
kind: Job
metadata:
  name: seed
spec:
  template:
    metadata:
      labels:
        app: seed
    spec:
      restartPolicy: Never 
      containers:
        - name: seed
          image: eloip13009/seed-data
          env:
            - name: TARGET_HOST
              value: "vote"
            - name: TARGET_PORT
              value: "5000"
