apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deployment
spec:
  replicas: 3
  template:
    metadata:
      name: vote
      labels:
        app: vote
    spec:
      containers:
      - image: europe-west9-docker.pkg.dev/login-ue-cloud-k8s/voting-image/vote
        name: vote
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
  selector:
    matchLabels:
      app: vote
