apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  selector:
    matchLabels:
      app: worker
  replicas: 3
  template:
    metadata:
      name: worker
      labels:
        app: worker
    spec:
      containers:
        - image: europe-west9-docker.pkg.dev/tuto-kube/voting-image/worker
          name: worker
