apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 3
  template:
    metadata:
      name: worker
      labels:
        app: worker
    spec:
      containers:
      - image: europe-west9-docker.pkg.dev/login-ue-cloud-k8s/voting-image/worker
        name: worker
  selector:
    matchLabels:
      app: worker
